### PR TITLE
New window work now

### PR DESCRIPTION
**Pull request by Jesse205**
The previous version would top off the main window on my phone. Now I fixed it.

### CODE REVIEW

**Comment by F0x1d** [comment]
But now LogFox has an expected behavior, why would you open all documents to in one window?

**Comment by F0x1d** [comment]
But what will this PR change then? It will just make only 1 window for opening documents instead of many

**Comment by Jesse205** [comment]
I can open many windows on my end. This requires opening a different file to open a new window

**Comment by F0x1d** [comment]
That looks like the problem of your ROM or file viewer, they should use new window flag or something in intent

**Comment by Jesse205** [comment]
I have this issue on both HarmonyOS (EMUI) and MIUI devices. I just tested it and it requires third-party applications to not add new task flags in order to function properly.

**Comment by F0x1d** [comment]
Both are not the best ROMs to check :) Anyway, it looks like this is not the LogFox problem

**Comment by Jesse205** [comment]
I'm very sorry, this is the code I copied directly from above. I have changed it now

**Comment by F0x1d** [comment]
What are talking about?

**Comment by Jesse205** [comment]
I'm very sorry, this is another PR response. I've made too many mistakes lately.

**Pull request closed without merging**
