### PR TITLE
Optimize the display of navigation bar and cutout

### PR DESCRIPTION
**Pull request by Jesse205**
- Apply transparent when navigation shown
- Apply navigation bar contrast on earlier android
- Make layout behind camera

### CODE REVIEW

**Comment by F0x1d** [comment]
Isn't it already implemented? Anyway, the code was completely reformatted, i can't accept it

**Comment by Jesse205** [comment]
The latest version still has some issues
- On my device with a perforated screen, the layout cannot be placed under the camera when facing horizontally

- On non Huawei devices, the navigation bar will always be at the bottom of the phone, so during the rotation process, the navigation bar may be on the left side of the layout, which conflicts with the original filling of the rail

- Due to the transparent navigation bar of the application, the navigation bar buttons may not be visible clearly

**Comment by Jesse205** [comment]
I cannot consume the navigation bar on one side alone. I would rather recommend refactoring to address the issue of rail paddings.

**Comment by F0x1d** [comment]
Still, the code is completely refactored and I don't like this code style. I can't accept it. 

Looks like I'll pick the changes from the PR and implement them myself

**Comment by F0x1d** [comment]
Implemented some of the things in 9fab8f4f0631f3a7784ab45d95879482875fea4a

**Pull request closed without merging**
