### PR TITLE
Turkish translation 

### PR DESCRIPTION
**Pull request by Baturax**
fixed

### CODE REVIEW

**Comment by F0x1d** [comment]
This is not a full translation?

**Comment by Baturax** [comment]
> This is not a full translation?

Didn't you tell me to remove translatable="false" lines

**Comment by F0x1d** [comment]
Yeah, but check your strings.xml file, more than a half of lines are in English

**Comment by Baturax** [comment]
> Yeah, but check your strings.xml file, more than a half of lines are in English

ooh, you are right. i have forgotten to save the file 😔 i will do it again

**Pull request closed without merging**
